name = "fad"
version = "0.1.0"
defaultTargets = ["fad"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso.git"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[leanOptions]
#weak.verso.examples.suggest = true
weak.linter.typography.quotes = true
weak.linter.typography.dashes = true
weak.linter.verso.manual.headerTags = true

[[lean_lib]]
name = "Fad"

[[lean_lib]]
name = "Book"

[[lean_exe]]
name = "fad"
root = "Main"

[[lean_exe]]
name = "book"
root = "MainBook"


