name = "fad"
version = "0.1.0"
defaultTargets = ["Fad"]

[[lean_lib]]
name = "Fad"

[[lean_exe]]
name = "main"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.24.0"
